name: Deploy

on: 
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checkout Code
    - name: Checkout Source Code
      uses: actions/checkout@v3

    # Create wp-config.php file 
    - name: Create WP Config
      run: |
        cp wp-config-sample.php wp-config.php
        sed -i 's/database_name_here/${{ secrets.DB_NAME }}/g' wp-config.php
      shell: bash

    - name: rsync deployments
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete
        path: ./
        remote_path: /var/www/html/
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_key: ${{ secrets.SSH_KEY }}

